version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  node: bigcommerce/internal-node@volatile

node_executor: &node_executor
  docker:
    - image: circleci/node:10
node_browser_executor: &node_browser_executor
  docker:
    - image: circleci/node:10-browsers

commands:
  install-dependencies:
    steps:
      - ci/pre-setup
      - node/yarn-install:
          cache_key: v2
  unit-test:
    steps:
      - run:
          name: Unit Tests # Jest unit tests
          command: yarn test:ci
      - store_test_results:
          path: ./test-reports
  functional-test:
    steps:
      - run:
          name: Functional Tests # CodeceptJS functional tests
          command: yarn functional:ci
      - store_test_results:
          path: ./test-reports
      - store_artifacts:
          path: ./test-reports

jobs:
  unit-tests:
    <<: *node_executor
    resource_class: small
    steps:
      - install-dependencies
      - unit-test
  functional-tests:
    <<: *node_browser_executor
    resource_class: small
    steps:
    - install-dependencies
    - functional-test

workflows:
  full:
    jobs:
      - unit-tests
      - functional-tests
